import { Inter } from 'next/font/google';
import Navbar from '../../components/Navbar';
import Head from 'next/head';
import SocialButton from '../../components/SocialButton';
import Linkedin from '../../public/linkedin.svg'
import Instagram from '../../public/instagram.svg'
import Youtube from '../../public/youtube.svg'
import Github from '../../public/github.svg'
import ProjectPreview from '../../components/ProjectPreview';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
    <Head>
        <title>My portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Navbar/>
    
    
    <section className="grid overflow-x-hidden grid-cols-1 lg:grid-cols-[2fr_1fr] gap-4 mb-4">
        <div className='h-[30rem] rounded-3xl p-10 flex flex-col gap-16 bg-[url("/gradient-bg.jpg")] bg-cover'>
            <h1 className='text-4xl font-semibold'>Hello, I'm a Software ENgineer with 4 years of experience.</h1>
            <p className='flex-1'>
           Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas massa nisi, rhoncus vitae tellus quis, lacinia aliquam eros. Donec eleifend interdum augue.
            </p>
            <div className='flex flex-col lg:flex-row items-center gap-4 justify-self-end'>
                <button className='bg-black text-white font-medium py-3 px-12 rounded-full w-60 lg:w-auto'>Contact Me</button>
                <div className='flex items-center gap-4'>
                    <SocialButton bgColor='github'>
                        <Github className="w-5 h-5" />
                    </SocialButton>
                    <SocialButton bgColor='linkedin'>
                        <Linkedin className="w-5 h-5" />
                    </SocialButton>
                    <SocialButton bgColor='instagram'>
                        <Instagram className="w-5 h-5" />
                    </SocialButton>
                    <SocialButton bgColor='youtube'>
                        <Youtube className="w-5 h-5" />
                    </SocialButton>
                </div>
            </div>
        </div>
        <div className='h-[30rem] rounded-3xl p-8 bg-[url("/profile.jpg")] bg-cover bg-center'></div>
    </section>

    <section className="grid grid-cols-1 lg:grid-cols-2 gap-4 my-4">
        <ProjectPreview
          name="Flip App"
          description="Next-gen social media"
          imageUrl="/project-1.png"
          bgColor="#685cdd"
          dark
        />
        <ProjectPreview
          name="Moneyscape"
          description="Lend and borrow dashboard"
          imageUrl="/project-2.png"
          bgColor="#313442"
          dark
        />
        <ProjectPreview
          name="Admin Onboarding"
          description="Increase user engagement"
          imageUrl="/project-3.png"
        />
        <ProjectPreview
          name="Project Dashboard"
          description="Project management app"
          bgColor="#4e4e56"
          dark
        />
        <ProjectPreview
          name="Newsy App"
          description="News aggregator app"
          imageUrl="/project-2.png"
          bgColor="#171717"
          dark
        />
        <ProjectPreview
          name="Krypto"
          description="Analyze crypto currency"
          imageUrl="/project-3.png"
        />
      </section>
  </>
  )
}
